### ISSUE TITLE
Docs: MathJax not loaded -> math not rendered

### ISSUE THREAD

**Issue by zmoon** [psu-inversion/atmospheric-inverse-methods-for-flux-optimization#42]
**Describe the bug**
In the rendered docs at https://psu-inversion.github.io/atmospheric-inverse-methods-for-flux-optimization/
math does not display correctly because MathJax is not being loaded.

I tested inserting this snippet into a page's `<head>`
```
  <!-- MathJax Support -->
  <script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>
```
and it worked then.

Maybe you could set `mathjax_path` explicitly in your conf?

**Comment by zmoon** [comment]
I see that the version there (in the rendered docs) is a bit behind what you have here though, so perhaps you already fixed this...

**Comment by DWesl** [comment]
I haven't touched the docs in a few weeks.  I thought I'd fixed the sphinx config so this wasn't necessary a few months ago.
Edit: It looks like the config fix went in in late March (362dc14), which means it should have been included in #38.  I have no idea what went wrong.

I just uploaded a new version, currently in #43, which mentions MathJax a bunch so hopefully it fixes the problem.  
Could you check to see if that fixes your issue, or at least contains your solution?

**Comment by zmoon** [comment]
Yeah, I think it should be fine now, since MathJax is being loaded from CDN.

But since you have a config elsewhere you could remove the `?config=TeX-MML-AM_CHTML` from the CDN URL, although [that configuration](https://docs.mathjax.org/en/v2.7-latest/config-files.html#the-tex-mml-am-htmlormml-configuration-file) is pretty similar to (just expanded) the one you specify in https://github.com/psu-inversion/atmospheric-inverse-methods-for-flux-optimization/blob/e5ec38b43fb8e36a4f2c8132a654fd6a5569767c/doc/source/conf.py#L132
which is now showing up in the HTML.

**Comment by zmoon** [comment]
ee8cde7dd9777c0b0409047f0ddc283d1a8465c0 seems like a good choice given [the MathJax changes](http://docs.mathjax.org/en/latest/upgrading/v2.html) you mention / Sphinx 4

**Comment by DWesl** [comment]
I just checked that the TeX input parser will continue to include the AMS math packages, so this change should be reasonably future-proof.  Any other obvious mistakes I should fix before merging?

**Comment by zmoon** [comment]
Not that I see. Excited to check out the theory section after this fix, seems like nice stuff.

**Comment by DWesl** [comment]
Okay, the theory should be much more readable now.
I've pretty much only focused on how to derive the equations, so hopefully things make sense.
